image: $REGISTRY_SERVER/docker:dind
services:
  - name: $REGISTRY_SERVER/docker:dind
    command:
      - /bin/sh
      - -c
      - |
        echo "$REGISTRY_SERVER_IP  $REGISTRY_SERVER" >> /etc/hosts
        echo "$GIT_SERVER_IP  git.sua.go.tz" >> /etc/hosts
        mkdir -p /etc/docker/certs.d/$REGISTRY_SERVER/
        echo "$REGISTRY_SERVER_CA" > /etc/docker/certs.d/$REGISTRY_SERVER/ca.crt
        cp /etc/docker/certs.d/$REGISTRY_SERVER/ca.crt /usr/local/share/ca-certificates/$REGISTRY_SERVER && update-ca-certificates
        dockerd-entrypoint.sh || exit 
stages:
  - build
  - test
  - deploy

variables:
  # Set up environment variables
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"

# Define job for building the application
build:
  stage: build
  image: python:3.9
  before_script:
    - python -m pip install --upgrade pip
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - .venv/

# Define job for running tests
test:
  stage: test
  image: python:3.9
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade pytest
  script:
    - pytest tests/

# Define job for deployment
deploy:
  stage: deploy
  image: python:3.9
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python deploy.py
  only:
    - master
