apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registration.fullname" . }}
  labels:
    {{- include "registration.labels" . | nindent 4 }}
  annotations:
    {{- include "registration.deploymentAnnotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "registration.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "registration.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "registration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "registration.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if eq .Values.image.versioning true }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.repository }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ required "Container port required!" .Values.service.targetPort }}
              protocol: TCP
          {{- if or (eq .Values.configMap.enabled true) (eq .Values.secret.enabled true) }}
          envFrom:
            {{- if .Values.configMap.enabled }}
            {{- range .Values.configMap.name }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            {{- if or .Values.secret.enabled .Values.secret.name }}
            {{- range .Values.secret.name }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end}}
          {{- end }}
          {{- if eq .Values.probes.enabled true }}
          {{- if or (eq .Values.probes.type "Liveness") (eq .Values.probes.type "Both") }}
          livenessProbe:
          {{- if eq .Values.probes.mode "http" }}
            {{- toYaml .Values.probes.httpLive  | nindent 12 }}
          {{- end }}
          {{- if eq .Values.probes.mode "tcp" }}
            {{- toYaml .Values.probes.tcpLive  | nindent 12 }}
          {{- end }}
          {{- if eq .Values.probes.mode "exec" }}
            {{- toYaml .Values.probes.execLive  | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.options }}
            {{- toYaml .  | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if or (eq .Values.probes.type "Readiness") (eq .Values.probes.type "Both") }}
          readinessProbe:
          {{- if eq .Values.probes.mode "http" }}
            {{- toYaml .Values.probes.httpLive  | nindent 12 }}
          {{- end }}
          {{- if eq .Values.probes.mode "tcp" }}
            {{- toYaml .Values.probes.tcpLive  | nindent 12 }}
          {{- end }}
          {{- if eq .Values.probes.mode "exec" }}
            {{- toYaml .Values.probes.execLive  | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.options }}
            {{- toYaml .  | nindent 12 }}
          {{- end }}
          {{- end }}    
          {{- end }}
          {{- if .Values.volumeMount }}
          volumeMounts:
            {{- toYaml .Values.volumeMount | nindent 12}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if or .Values.volumes.claim .Values.volumes.secret }}
      volumes:
    {{- if .Values.volumes.claim }}
      {{- toYaml .Values.volumes.claim | nindent 8 }}
    {{- end }}
    {{- if .Values.volumes.secret }}
      {{- toYaml .Values.volumes.secret | nindent 8 }}
    {{- end }}
    {{- if .Values.volumes.config }}
      {{- toYaml .Values.volumes.config | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if eq .Values.initContainers.enabled true }}
      initContainers:
        {{- toYaml .Values.initContainers.init | nindent 8 }}
    {{- end }}
