{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "registration.fullname" . }}
data:
  {{- if .Values.secret.credentials.database }}
  {{- if eq .Values.secret.credentials.database.type "postgres" }}
  POSTGRES_USER: {{ .Values.secret.credentials.database.dbUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.credentials.database.dbPass | b64enc }}
  PGPASSWORD: {{ .Values.secret.credentials.database.dbPass | b64enc }}
  {{- else if eq .Values.secret.credentials.database.type "mongo" }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secret.credentials.database.dbUser | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secret.credentials.database.dbPass | b64enc }}
  {{- else if eq .Values.secret.credentials.database.type "mongo_app" }}
  MONGO_USERNAME: {{ .Values.secret.credentials.database.dbUser | b64enc }}
  MONGO_PASSWD: {{ .Values.secret.credentials.database.dbPass | b64enc }}
  {{- else }}
  DB_USER: {{ .Values.secret.credentials.database.dbUser | b64enc }}
  DB_PASS: {{ .Values.secret.credentials.database.dbPass | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.secret.cert }}
  PRIVATE_KEY: {{ .Values.secret.cert.privateKey | b64enc }}
  {{- end }}
  {{- if .Values.secret.credentials.application }}
  GEPG_KEY_STORE_PASSWORD: {{ .Values.secret.credentials.application.gepgKeyPassword | b64enc }}
  GEPG_KEY_STORE_PUBLIC_PASSWORD: {{ .Values.secret.credentials.application.gepgKeyPubPassword | b64enc }}
  PRIVATE_KEY_PASS: {{ .Values.secret.credentials.application.privateKeyPass | b64enc }}  
  PUBLIC_KEY_PASS: {{ .Values.secret.credentials.application.publicKeyPass | b64enc }}
  {{- end }}
  {{- if .Values.secret.credentials.ldap }}
  LDAP_USERNAME: {{ .Values.secret.credentials.ldap.ldapuser | b64enc }}
  LDAP_PASSWORD: {{ .Values.secret.credentials.ldap.ldappass | b64enc }}
  {{- end }}
{{- end -}}  
