"""Add new delay Reasons on Procedure Records

Revision ID: 19dbe04106c4
Revises: 8c8d8d4e0ef4
Create Date: 2026-06-15 11:39:11.127111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dbe04106c4'
down_revision: Union[str, None] = '8c8d8d4e0ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatre_procedure_records', sa.Column('delay_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theatre_procedure_records', 'delay_reason')
    # ### end Alembic commands ###