"""first migration

Revision ID: 45ce24c3a338
Revises: 
Create Date: 2026-06-12 11:10:41.119185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ce24c3a338'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('death_reasons',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_death_reasons_id'), 'death_reasons', ['id'], unique=False)
    op.create_index(op.f('ix_death_reasons_uid'), 'death_reasons', ['uid'], unique=True)
    op.create_table('internal_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_sources_id'), 'internal_sources', ['id'], unique=False)
    op.create_index(op.f('ix_internal_sources_uid'), 'internal_sources', ['uid'], unique=True)
    op.create_table('procedure_delay_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_procedure_delay_categories_id'), 'procedure_delay_categories', ['id'], unique=False)
    op.create_index(op.f('ix_procedure_delay_categories_uid'), 'procedure_delay_categories', ['uid'], unique=True)
    op.create_table('procedures',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_id'), 'procedures', ['id'], unique=False)
    op.create_index(op.f('ix_procedures_uid'), 'procedures', ['uid'], unique=True)
    op.create_table('regions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_uid'), 'regions', ['uid'], unique=True)
    op.create_table('theatre_members',
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('pf_number', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatre_members_id'), 'theatre_members', ['id'], unique=False)
    op.create_index(op.f('ix_theatre_members_pf_number'), 'theatre_members', ['pf_number'], unique=False)
    op.create_index(op.f('ix_theatre_members_uid'), 'theatre_members', ['uid'], unique=True)
    op.create_table('theatre_roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatre_roles_id'), 'theatre_roles', ['id'], unique=False)
    op.create_index(op.f('ix_theatre_roles_uid'), 'theatre_roles', ['uid'], unique=True)
    op.create_table('theatre_units',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatre_units_id'), 'theatre_units', ['id'], unique=False)
    op.create_index(op.f('ix_theatre_units_uid'), 'theatre_units', ['uid'], unique=True)
    op.create_table('external_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('region_uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_uid'], ['regions.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_sources_id'), 'external_sources', ['id'], unique=False)
    op.create_index(op.f('ix_external_sources_uid'), 'external_sources', ['uid'], unique=True)
    op.create_table('procedure_delay_causes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('procedure_delay_category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_delay_category_id'], ['procedure_delay_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_delay_causes_id'), 'procedure_delay_causes', ['id'], unique=False)
    op.create_index(op.f('ix_procedure_delay_causes_procedure_delay_category_id'), 'procedure_delay_causes', ['procedure_delay_category_id'], unique=False)
    op.create_index(op.f('ix_procedure_delay_causes_uid'), 'procedure_delay_causes', ['uid'], unique=True)
    op.create_table('theatre_member_roles',
    sa.Column('member_uid', sa.UUID(), nullable=False),
    sa.Column('role_uid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_uid'], ['theatre_members.uid'], ),
    sa.ForeignKeyConstraint(['role_uid'], ['theatre_roles.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatre_member_roles_id'), 'theatre_member_roles', ['id'], unique=False)
    op.create_index(op.f('ix_theatre_member_roles_uid'), 'theatre_member_roles', ['uid'], unique=True)
    op.create_table('theatre_procedure_records',
    sa.Column('patient_mrn', sa.String(length=100), nullable=True),
    sa.Column('patient_dob', sa.Date(), nullable=True),
    sa.Column('patient_sex', sa.String(length=10), nullable=True),
    sa.Column('patient_region', sa.UUID(), nullable=True),
    sa.Column('patient_type', sa.Enum('ELECTIVE', 'EMERGENCY', name='patienttype'), nullable=False),
    sa.Column('patient_source_type', sa.Enum('INTERNAL', 'EXTERNAL', name='sourcetype'), nullable=False),
    sa.Column('internal_source_id', sa.Integer(), nullable=True),
    sa.Column('external_source_id', sa.Integer(), nullable=True),
    sa.Column('theatre_unit_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('procedure_date', sa.Date(), nullable=False),
    sa.Column('procedure_start_time', sa.Time(), nullable=False),
    sa.Column('procedure_end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('variance_minutes', sa.Integer(), nullable=True),
    sa.Column('met_turnaround_target', sa.Boolean(), nullable=True),
    sa.Column('had_delay', sa.Boolean(), nullable=False),
    sa.Column('surgery_beyond_theatre_time', sa.Boolean(), nullable=True),
    sa.Column('surgery_met_time_between_cases', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.Enum('DEATH', 'DISCHARGED', name='patientoutcome'), nullable=False),
    sa.Column('discharge_direction', sa.Enum('INTERNAL', 'HOME', name='dischargedirection'), nullable=True),
    sa.Column('discharge_destination_id', sa.Integer(), nullable=True),
    sa.Column('death_reason_id', sa.Integer(), nullable=True),
    sa.Column('death_description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['death_reason_id'], ['death_reasons.id'], ),
    sa.ForeignKeyConstraint(['discharge_destination_id'], ['internal_sources.id'], ),
    sa.ForeignKeyConstraint(['external_source_id'], ['external_sources.id'], ),
    sa.ForeignKeyConstraint(['internal_source_id'], ['internal_sources.id'], ),
    sa.ForeignKeyConstraint(['patient_region'], ['regions.uid'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['theatre_unit_id'], ['theatre_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatre_procedure_records_discharge_direction'), 'theatre_procedure_records', ['discharge_direction'], unique=False)
    op.create_index(op.f('ix_theatre_procedure_records_had_delay'), 'theatre_procedure_records', ['had_delay'], unique=False)
    op.create_index(op.f('ix_theatre_procedure_records_id'), 'theatre_procedure_records', ['id'], unique=False)
    op.create_index(op.f('ix_theatre_procedure_records_outcome'), 'theatre_procedure_records', ['outcome'], unique=False)
    op.create_index(op.f('ix_theatre_procedure_records_patient_region'), 'theatre_procedure_records', ['patient_region'], unique=False)
    op.create_index(op.f('ix_theatre_procedure_records_patient_type'), 'theatre_procedure_records', ['patient_type'], unique=False)
    op.create_index(op.f('ix_theatre_procedure_records_procedure_date'), 'theatre_procedure_records', ['procedure_date'], unique=False)
    op.create_index(op.f('ix_theatre_procedure_records_procedure_id'), 'theatre_procedure_records', ['procedure_id'], unique=False)
    op.create_index(op.f('ix_theatre_procedure_records_theatre_unit_id'), 'theatre_procedure_records', ['theatre_unit_id'], unique=False)
    op.create_index(op.f('ix_theatre_procedure_records_uid'), 'theatre_procedure_records', ['uid'], unique=True)
    op.create_table('theatre_record_delays',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['procedure_delay_categories.id'], ),
    sa.ForeignKeyConstraint(['cause_id'], ['procedure_delay_causes.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['theatre_procedure_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatre_record_delays_id'), 'theatre_record_delays', ['id'], unique=False)
    op.create_index(op.f('ix_theatre_record_delays_record_id'), 'theatre_record_delays', ['record_id'], unique=False)
    op.create_index(op.f('ix_theatre_record_delays_uid'), 'theatre_record_delays', ['uid'], unique=True)
    op.create_table('theatre_record_team_members',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('theatre_member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SURGEON', 'ANESTHETIST', 'SCRUB_NURSE', 'RUNNER_NURSE', name='teamrole'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['theatre_procedure_records.id'], ),
    sa.ForeignKeyConstraint(['theatre_member_id'], ['theatre_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatre_record_team_members_id'), 'theatre_record_team_members', ['id'], unique=False)
    op.create_index(op.f('ix_theatre_record_team_members_record_id'), 'theatre_record_team_members', ['record_id'], unique=False)
    op.create_index(op.f('ix_theatre_record_team_members_role'), 'theatre_record_team_members', ['role'], unique=False)
    op.create_index(op.f('ix_theatre_record_team_members_theatre_member_id'), 'theatre_record_team_members', ['theatre_member_id'], unique=False)
    op.create_index(op.f('ix_theatre_record_team_members_uid'), 'theatre_record_team_members', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theatre_record_team_members_uid'), table_name='theatre_record_team_members')
    op.drop_index(op.f('ix_theatre_record_team_members_theatre_member_id'), table_name='theatre_record_team_members')
    op.drop_index(op.f('ix_theatre_record_team_members_role'), table_name='theatre_record_team_members')
    op.drop_index(op.f('ix_theatre_record_team_members_record_id'), table_name='theatre_record_team_members')
    op.drop_index(op.f('ix_theatre_record_team_members_id'), table_name='theatre_record_team_members')
    op.drop_table('theatre_record_team_members')
    op.drop_index(op.f('ix_theatre_record_delays_uid'), table_name='theatre_record_delays')
    op.drop_index(op.f('ix_theatre_record_delays_record_id'), table_name='theatre_record_delays')
    op.drop_index(op.f('ix_theatre_record_delays_id'), table_name='theatre_record_delays')
    op.drop_table('theatre_record_delays')
    op.drop_index(op.f('ix_theatre_procedure_records_uid'), table_name='theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_procedure_records_theatre_unit_id'), table_name='theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_procedure_records_procedure_id'), table_name='theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_procedure_records_procedure_date'), table_name='theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_procedure_records_patient_type'), table_name='theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_procedure_records_patient_region'), table_name='theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_procedure_records_outcome'), table_name='theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_procedure_records_id'), table_name='theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_procedure_records_had_delay'), table_name='theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_procedure_records_discharge_direction'), table_name='theatre_procedure_records')
    op.drop_table('theatre_procedure_records')
    op.drop_index(op.f('ix_theatre_member_roles_uid'), table_name='theatre_member_roles')
    op.drop_index(op.f('ix_theatre_member_roles_id'), table_name='theatre_member_roles')
    op.drop_table('theatre_member_roles')
    op.drop_index(op.f('ix_procedure_delay_causes_uid'), table_name='procedure_delay_causes')
    op.drop_index(op.f('ix_procedure_delay_causes_procedure_delay_category_id'), table_name='procedure_delay_causes')
    op.drop_index(op.f('ix_procedure_delay_causes_id'), table_name='procedure_delay_causes')
    op.drop_table('procedure_delay_causes')
    op.drop_index(op.f('ix_external_sources_uid'), table_name='external_sources')
    op.drop_index(op.f('ix_external_sources_id'), table_name='external_sources')
    op.drop_table('external_sources')
    op.drop_index(op.f('ix_theatre_units_uid'), table_name='theatre_units')
    op.drop_index(op.f('ix_theatre_units_id'), table_name='theatre_units')
    op.drop_table('theatre_units')
    op.drop_index(op.f('ix_theatre_roles_uid'), table_name='theatre_roles')
    op.drop_index(op.f('ix_theatre_roles_id'), table_name='theatre_roles')
    op.drop_table('theatre_roles')
    op.drop_index(op.f('ix_theatre_members_uid'), table_name='theatre_members')
    op.drop_index(op.f('ix_theatre_members_pf_number'), table_name='theatre_members')
    op.drop_index(op.f('ix_theatre_members_id'), table_name='theatre_members')
    op.drop_table('theatre_members')
    op.drop_index(op.f('ix_regions_uid'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_procedures_uid'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_id'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_index(op.f('ix_procedure_delay_categories_uid'), table_name='procedure_delay_categories')
    op.drop_index(op.f('ix_procedure_delay_categories_id'), table_name='procedure_delay_categories')
    op.drop_table('procedure_delay_categories')
    op.drop_index(op.f('ix_internal_sources_uid'), table_name='internal_sources')
    op.drop_index(op.f('ix_internal_sources_id'), table_name='internal_sources')
    op.drop_table('internal_sources')
    op.drop_index(op.f('ix_death_reasons_uid'), table_name='death_reasons')
    op.drop_index(op.f('ix_death_reasons_id'), table_name='death_reasons')
    op.drop_table('death_reasons')
    # ### end Alembic commands ###