"""region changes

Revision ID: 478ead036040
Revises: 45ff2b528118
Create Date: 2026-06-13 14:42:23.780291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478ead036040'
down_revision: Union[str, None] = '45ff2b528118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_sources', sa.Column('region_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_external_sources_region_id'), 'external_sources', ['region_id'], unique=False)
    op.drop_constraint('external_sources_region_uid_fkey', 'external_sources', type_='foreignkey')
    op.create_foreign_key(None, 'external_sources', 'regions', ['region_id'], ['id'])
    op.drop_column('external_sources', 'region_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_sources', sa.Column('region_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'external_sources', type_='foreignkey')
    op.create_foreign_key('external_sources_region_uid_fkey', 'external_sources', 'regions', ['region_uid'], ['uid'])
    op.drop_index(op.f('ix_external_sources_region_id'), table_name='external_sources')
    op.drop_column('external_sources', 'region_id')
    # ### end Alembic commands ###