"""update Procedure Records Member Add  Rank Column

Revision ID: 8c8d8d4e0ef4
Revises: 936fe9594423
Create Date: 2026-06-15 09:29:59.523226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8d8d4e0ef4'
down_revision: Union[str, None] = '936fe9594423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatre_record_team_members', sa.Column('rank', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_theatre_record_team_members_rank'), 'theatre_record_team_members', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theatre_record_team_members_rank'), table_name='theatre_record_team_members')
    op.drop_column('theatre_record_team_members', 'rank')
    # ### end Alembic commands ###