"""first migration

Revision ID: 8e4552cd3cdd
Revises: 45ce24c3a338
Create Date: 2026-06-12 14:22:28.287136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4552cd3cdd'
down_revision: Union[str, None] = '45ce24c3a338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('theatre_record_delays_category_id_fkey', 'theatre_record_delays', type_='foreignkey')
    op.drop_column('theatre_record_delays', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatre_record_delays', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('theatre_record_delays_category_id_fkey', 'theatre_record_delays', 'procedure_delay_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###