"""update from region uid to id on theatre record

Revision ID: 936fe9594423
Revises: 478ead036040
Create Date: 2026-06-15 06:56:25.526959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936fe9594423'
down_revision: Union[str, None] = '478ead036040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatre_procedure_records', sa.Column('patient_region_id', sa.Integer(), nullable=True))
    op.drop_index('ix_theatre_procedure_records_patient_region', table_name='theatre_procedure_records')
    op.create_index(op.f('ix_theatre_procedure_records_patient_region_id'), 'theatre_procedure_records', ['patient_region_id'], unique=False)
    op.drop_constraint('theatre_procedure_records_patient_region_fkey', 'theatre_procedure_records', type_='foreignkey')
    op.create_foreign_key(None, 'theatre_procedure_records', 'regions', ['patient_region_id'], ['id'])
    op.drop_column('theatre_procedure_records', 'patient_region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatre_procedure_records', sa.Column('patient_region', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'theatre_procedure_records', type_='foreignkey')
    op.create_foreign_key('theatre_procedure_records_patient_region_fkey', 'theatre_procedure_records', 'regions', ['patient_region'], ['uid'])
    op.drop_index(op.f('ix_theatre_procedure_records_patient_region_id'), table_name='theatre_procedure_records')
    op.create_index('ix_theatre_procedure_records_patient_region', 'theatre_procedure_records', ['patient_region'], unique=False)
    op.drop_column('theatre_procedure_records', 'patient_region_id')
    # ### end Alembic commands ###